version: "3.9"
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  accrual:
    build:
      dockerfile: DockerfileAccrualMock
      context: .
    restart: always
    ports:
      - "8080:8080"
  gophermart:
      build:
        dockerfile: DockerfileGophermart
        context: .
      restart: always
      environment:
        - DATABASE_URI=host=host.docker.internal port=5432 user=postgres password=postgres dbname=postgres sslmode=disable
        - RUN_ADDRESS=:8787
        - ACCRUAL_SYSTEM_ADDRESS=http://host.docker.internal:8080
      volumes:
        - .:/opt/app/api
      ports:
        - "8787:8787"
volumes:
   db:
     driver: local